set_languages("c++23")
set_toolchains("clang")

-- target("bridge")
--     set_kind("shared")
--     add_files("bridge/src/*.cpp")
--     add_includedirs("bridge/include/")
--     add_includedirs("base/include/")


target("view")
    set_kind("binary")
    -- add_deps("bridge")
    on_build(function (target)
        local oldir = os.cd("./view")
        os.exec("pnpm build")
        os.cd(oldir)
        oldir = os.cd("./tauri-bridge")
        os.exec("cargo tauri build")
        os.cd(oldir)
    end)
    after_build(function (target) 
        local oldir = os.cd("./tauri-bridge")
        os.mv("./target/release/view.exe", "$(buildir)/")
        os.mv("./target/release/view.pdb", "$(buildir)/")
        os.cd(oldir)
    end)